name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        command: ['lint:ci', 'typecheck']

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build (1/2)
        run: bun install --frozen-lockfile
        continue-on-error: true

      - name: Build (2/2)
        run: bun install --frozen-lockfile

      - name: ${{ matrix.command }}
        run: bun run ${{ matrix.command }}
